# Generated by Django 3.1.3 on 2021-01-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('ingreso', models.IntegerField(verbose_name='Cantidad Ingresada')),
                ('ubicacion_actual', models.CharField(max_length=15, null=True, verbose_name='Ubicacion Actual')),
            ],
        ),
    ]
