# Generated by Django 3.1.3 on 2021-01-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='ubicacion_actual',
            field=models.CharField(max_length=15, null=True, verbose_name='Ubicacion Actual'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ubicacion_anterior',
            field=models.CharField(max_length=15, null=True, verbose_name='Ubicacion Anterior'),
        ),
    ]
